import argparse
import re

def main():
    '''Parse DLL Export Viewer .html output and print linkers to add to DLL proxy file'''

    parser = argparse.ArgumentParser(description="DLL Export Viewer - Report Parser")
    parser.add_argument("report", help="The HTML report generated by DLL Export Viewer")
    args = parser.parse_args()
    report = args.report

    try:
        f = open(report)
        page = f.readlines()
        f.close()
    except:
        print("[-] ERROR: open('%s')" % report)
        return

    
    fname_pat = r"\">(\w+)<\/td>"
    ordinal_pat = r"([0-9]+)\s"
    dllname_pat = r"\w+\.dll"
    for line in page:
        if '.dll' in line:
            function_name = re.search(fname_pat, line).group(1)
            ordinal = re.search(ordinal_pat, line).group(1)
            dll_name = re.findall(dllname_pat, line)[0].split('.')[0]
            dll_rename = dll_name + "_orig"
            print("#pragma comment(linker,\"/export:%s=%s.%s,@%s\")" % (function_name, dll_rename, function_name, ordinal))

if __name__ == '__main__':
    main()
