import argparse
import re
from bs4 import BeautifulSoup

def main():
    '''Parse DLL Export Viewer .html output and print linkers to add to DLL proxy file'''

    parser = argparse.ArgumentParser(description="DLL Export Viewer - Report Parser")
    parser.add_argument("report", help="The HTML report generated by DLL Export Viewer")
    args = parser.parse_args()
    report = args.report

    try:
        with open(report) as fp:
            soup = BeautifulSoup(fp, "html.parser")
    except:
        print("[-] ERROR: open('%s')" % report)
        return


    table = soup.find("table")

    for row in table.find_all("tr")[1:]:
        col = row.find_all("td")
        function_name = col[0].text
        ordinal = col[3].text.split(" ")[0]
        dll_name = col[4].text.split('.dll')[0]
        dll_rename = dll_name + "_orig"
        print("#pragma comment(linker,\"/export:%s=%s.%s,@%s\")" % (function_name, dll_rename, function_name, ordinal))
  

if __name__ == '__main__':
    main()
